"""empty message

Revision ID: 4f34d720f535
Revises: 5207fb3bfe97
Create Date: 2026-02-10 00:11:42.030545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f34d720f535'
down_revision = '5207fb3bfe97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('IMAGE', 'VIDEO', 'GIF', name='mediatype', native_enum=False),
               existing_nullable=False)
        batch_op.drop_constraint('Media_type_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.create_unique_constraint('Media_type_key', ['type'])
        batch_op.alter_column('type',
               existing_type=sa.Enum('IMAGE', 'VIDEO', 'GIF', name='mediatype', native_enum=False),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.drop_table('follower')
    # ### end Alembic commands ###
